<%

' Path
Const STR_ASG_SKIN_PATH  = "includes/templates/default/" 'P-1
Const STR_ASG_SKIN_PATH_IMAGE  = "images/" 'P-1
' Global on each page
'Const STR_ASG_SKIN_PAGE_BGCOLOUR = "#F9F9F9" 'C-2
Const STR_ASG_SKIN_PAGE_BGCOLOUR  = "#FFFFFF" 'C-2
Const STR_ASG_SKIN_PAGE_BGIMAGE  = "" 'P-3
Const STR_ASG_SKIN_PAGE_WIDTH  = "100%" 'S-4
Const STR_ASG_SKIN_TABLE_WIDTH  = "95%" 'S-16
' Layout tables
Const STR_ASG_SKIN_TABLE_LAYOUT_BDCOLOUR  = "#999999" 'C-5
Const STR_ASG_SKIN_TABLE_LAYOUT_BGCOLOUR  = "#F6F6F6" 'C-6
Const STR_ASG_SKIN_TABLE_LAYOUT_BGIMAGE  = "" 'P-7
Const STR_ASG_SKIN_TABLE_BAR_BGCOLOUR  = "" 'C-8
Const STR_ASG_SKIN_TABLE_BAR_BGIMAGE  = "layout/bar_bg.jpg" 'P-9
' Data tables
Const STR_ASG_SKIN_TABLE_TITLE_BGCOLOUR  = "" 'C-10
Const STR_ASG_SKIN_TABLE_TITLE_BGIMAGE  = "layout/small_bar_bg.jpg" 'P-11
Const STR_ASG_SKIN_TABLE_CONT_BGCOLOUR  = "#ECEAF2" 'C-12
Const STR_ASG_SKIN_TABLE_CONT_BGIMAGE  = "" 'P-13
' Content rows rollover effect
Const STR_ASG_SKIN_TABLE_CONT_BGOVER  = "#DEDCE6" 'C-14
Const STR_ASG_SKIN_TABLE_CONT_BGOUT  = "#ECEAF2" 'C-15

%>
